name: first workflow
on: [push]
jobs: 
  build: 
    name: build job
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: build code
    - run: dotnet build
